title: Plataforma Web de SocioUnido
description: Documentacion de la plataforma de gestión web de "SocioUnido"
theme: just-the-docs

url: "https://trabajoprofesional-aggz.github.io"

baseurl: "/microservicio-pagos"
