export const PERMISO_LABELS = {
  'ver_socios':        'Ver socios',
  'crear_socio':       'Crear socio',
  'editar_socio':      'Editar socio',
  'borrar_socio':      'Dar de baja socio',
  'ver_usuarios':      'Ver usuarios',
  'crear_usuario':     'Crear usuario',
  'editar_usuario':    'Editar usuario',
  'borrar_usuario':    'Dar de baja usuario',
  'ver_reservas':      'Ver reservas',
  'crear_reserva':     'Crear reserva',
  'borrar_reserva':    'Dar de baja reserva',
  'crear_instalacion': 'Crear instalación',
  'ver_instalaciones': 'Ver instalaciones',
  'borrar_instalacion':'Dar de baja instalación',
  'crear_disciplina': 'Crear disciplina',
  'ver_disciplinas': 'Ver disciplinas',
  'borrar_disciplina': 'Dar de baja disciplina',
  'crear_noticia': 'Crear noticia',
  'ver_noticias': 'Ver noticias',
  'editar_noticia': 'Editar noticia',
  'borrar_noticia': 'Dar de baja noticia',
  'crear_alerta': 'Crear alerta',
  'ver_alertas': 'Ver alertas',
  'borrar_alerta': 'Dar de baja alerta',
  'ver_metricas': 'Ver las metricas del club',
  'ver_tramites': 'Ver trámites',
  'crear_evento': 'Crear evento',
  'ver_eventos': 'Ver eventos',
  'ver_pagos_pendientes': 'Ver pagos pendientes',
  'crear_entrada': 'Reservar entrada para socio'
};
